/** 
 * defines for modules
 */

#ifndef ERC_MODULESDEFINE_H
#define ERC_MODULESDEFINE_H

//Modules definition
#define MODULE_MOTOR_MBLAZE 10
#define MODULE_MOTOR_PHIDGETS 11
#define MODULE_MOTOR_SERIAL 12
#define MODULE_GPS 20
#define MODULE_LIDAR 30
#define MODULE_CAMERA 40
#define MODULE_COMPASS 50
#define MODULE_JOYSTICK 60
#define MODULE_JAUS 70
#define MODULE_PARALLELPORT 80

//DataType definition
#define DATATYPE_MOTORDATA 10
#define DATATYPE_GPSDATA 20
#define DATATYPE_LIDARDATA 30
#define DATATYPE_CAMERADATA 40
#define DATATYPE_CAMERAFRAME 41
#define DATATYPE_COMPASSDATA 50
#define DATATYPE_JOYSTICKDATA 60
#define DATATYPE_JAUSDATA 70
#define DATATYPE_PARALLELPORTDATA 80


#endif
