/**
 * Network Define for ERC
 */

#ifndef ERC_NETWORKDEFINE_H
#define ERC_NETWORKDEFINE_H

//network command define
#define NETWORK_CMD_UNKNOWN 0

#define NETWORK_CMD_DISCONNECT 1
#define NETWORK_CMD_DEBUG 2
#define NETWORK_CMD_ONLINE_CLIENT 3

#define NETWORK_CMD_MODULE_AVAILABLE 10
#define NETWORK_CMD_MODULE_LOADED 11
#define NETWORK_CMD_MODULE_STATUS 12
#define NETWORK_CMD_MODULE_LOAD 13
#define NETWORK_CMD_MODULE_UNLOAD 14
#define NETWORK_CMD_MODULE_GET 15
#define NETWORK_CMD_MODULE_SET 16
#define NETWORK_CMD_MODULE_ADD 17
#define NETWORK_CMD_MODULE_DELETE 18

#define NETWORK_CMD_CONTROL_STATUS 20
#define NETWORK_CMD_CONTROL_START 21
#define NETWORK_CMD_CONTROL_STOP 22

#define NETWORK_CMD_CONFIG_GET_STRING 30
#define NETWORK_CMD_CONFIG_SET_STRING 31
#define NETWORK_CMD_CONFIG_GET_DOUBLE 32
#define NETWORK_CMD_CONFIG_SET_DOUBLE 33
#define NETWORK_CMD_CONFIG_GET_BOOL 34
#define NETWORK_CMD_CONFIG_SET_BOOL 35
#define NETWORK_CMD_CONFIG_GET_INT 36
#define NETWORK_CMD_CONFIG_SET_INT 37

#define NETWORK_CMD_SYSTEM_HALT 255

//network return code
#define NETWORK_CODE_UNKNOWN 0
#define NETWORK_CODE_SUCCESS 1
#define NETWORK_CODE_SUCCESS_WITH_DATA 2

#define NETWORK_CODE_FAILURE 255
#define NETWORK_CODE_SYNTAX_ERROR 254

//status code
#define NETWORK_STATUS_UNKNOWN 0
#define NETWORK_STATUS_NOT_STARTED 1
#define NETWORK_STATUS_RUNNING 2
#define NETWORK_STATUS_STOP 3
#define NETWORK_STATUS_ERROR 4



#endif

